[package]
name = "hyperlight_testing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
hex-literal = "0.4"

[lib]
bench = false # see https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
