[workspace]
resolver = "2"
members = [
    "src/hyperlight_capi",
    "src/hyperlight_host",
    "src/hyperlight_testing",
    "src/hyperlight_flatbuffers",
]

# this will generate symbols for release builds
# so is handy for debugging issues in release builds
# to use, run `cargo build --profile=release-with-debug`
[profile.release-with-debug]
inherits = "release"
debug = true