[package]
name = "hyperlight_host"
version = "0.1.0"
edition = "2021"

[lib]
# https://docs.rust-embedded.org/book/interoperability/rust-with-c.html
name = "hyperlight_host"
# crate-type = ["staticlib"]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cty = { version="0.2.2" }
goblin = { version = "0.5.4" }
anyhow = { version = "1.0.64" }
byteorder = { version = "1.4.3" }
chashmap = { version = "2.2.2" }
rand = { version = "0.8.5" }
cfg-if = { version = "1.0.0" }
libc = { version = "0.2.132" }
windows = { version = "0.39.0", features = [
    "Win32_System_Memory",
    "Win32_Foundation"
] }

[target.'cfg(unix)'.dependencies]
mshv-bindings = {git = "https://github.com/rust-vmm/mshv", rev="a4c9916" }
mshv-ioctls  = {git = "https://github.com/rust-vmm/mshv", rev="a4c9916"}
kvm-bindings = { version = "0.5.0", features = ["fam-wrappers"] }
kvm-ioctls = { version = "0.11.0" }

[dev-dependencies]
pretty_assertions = { version = "1.3.0" }
more-asserts = { version = "0.3.0" }
envy = { version = "0.4.2" }
once_cell = { version = "1.14.0" }
serde =  { version = "1.0", features = ["derive"] }

[build-dependencies]
cbindgen = { version = "0.24.3" }
anyhow = { version = "1.0.64"}