[package]
name = "hyperlight_guest_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
flatbuffers = "23.5.26"
mimalloc = { version = "*", features = ["secure"] }
lazy_static = "1.4.0"
spin = "0.9.8"