[package]
name = "hyperlight_flatbuffers"
version = "0.1.0"
edition = "2021"

[dependencies]
flatbuffers = "23.5"
anyhow = "1"

[dev-dependencies]
hyperlight_testing = { path = "../hyperlight_testing" }