[package]
name = "hyperlight_guest_capi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["staticlib"]

[lints]
workspace = true

[dependencies]
hyperlight_guest = { path = "../hyperlight_guest", version = "0.9.0", registry = "hyperlight_packages" }
hyperlight_common = { path = "../hyperlight_common", default-features = false, version = "0.9.0", registry = "hyperlight_packages" }
log = { version = "0.4", default-features = false }

[build-dependencies]
cbindgen = "0.27.0"
