[profile.release]         
panic = 'abort'         # Always abort, this is mainly to ensure that panics cannot unwind across FFI boundaries.

[registries]
hyperlight_redist = { index = "sparse+https://pkgs.dev.azure.com/AzureContainerUpstream/hyperlight/_packaging/hyperlight_redist/Cargo/index/" }
hyperlight_packages = { index = "sparse+https://pkgs.dev.azure.com/AzureContainerUpstream/hyperlight/_packaging/hyperlight_packages_test/Cargo/index/" }

[registry]
global-credential-providers = ["cargo:token"]

