name: Benchmarks

on:
  workflow_call: # this is called from CreateRelease.yml
    secrets:
      ADO_CARGO_RO_PAT:
        required: true

jobs:
  build-host-library:
    uses: ./.github/workflows/dep_build_host_library.yml
    secrets: inherit
  build-guest-binaries:
    uses: ./.github/workflows/dep_build_guest_binaries.yml
    needs: [build-host-library]

  benchmark:
    needs: [build-guest-binaries]
    strategy:
      fail-fast: true
      matrix:
        build: [windows-2022-release, linux-kvm-release, linux-hyperv-release]
        include:
          - build: windows-2022-release
            os: [self-hosted, Windows, X64, "1ES.Pool=HL-Windows-2022"]
            hypervisor: none
          - build: linux-kvm-release
            os: [self-hosted, Linux, X64, "1ES.Pool=HL-Ubuntu-20.04-KVM"]
            hypervisor: kvm
          - build: linux-hyperv-release
            os: [self-hosted, Linux, X64, "1ES.Pool=HL-CBLMariner-mshv"]
            hypervisor: hyperv
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/hyperlight-workflows-setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT: ${{ secrets.ADO_CARGO_RO_PAT }}

      - name: Enable WHP on Windows
        if: ${{ (runner.os == 'Windows')}}
        run: Enable-WindowsOptionalFeature -Online -FeatureName HyperVisorPlatform
        shell: pwsh


      # Rust tests require the test binaries (simpleguest.exe, dummyguest.exe, 
      # etc...) to be in ./src/tests/Hyperlight.Tests/bin/{Release or Debug}/net6.0.
      # 
      # We have a dependency on the 'build-guest-binaries' job, which builds 
      # them and uploads them using the upload-artifact step. we're downloading
      # them here, then moving them to the right location in the subsequent step
      - name: Download Guest Binaries
        uses: actions/download-artifact@v3
        with:
          name: guest-binaries-release
          path: ./src/tests/Hyperlight.Tests/bin/release/net6.0

      - name: Copy Guest Binaries
        run: |
          echo "copying guest binaries for build config release"
          cp ./dummyguest/x64/release/dummyguest.exe dummyguest.exe
          cp ./simpleguest/x64/release/simpleguest.exe simpleguest.exe
          cp ./callbackguest/x64/release/callbackguest.exe callbackguest.exe
        working-directory: ./src/tests/Hyperlight.Tests/bin/release/net6.0

      - name: Display Guest Binaries
        run: |
          ls -R ./src/tests/Hyperlight.Tests/bin/release/net6.0
          
      - name: Set up env vars for hyperv-linux tests
        if: ${{ (matrix.hypervisor == 'hyperv') && (runner.os == 'Linux') }}
        run: |
          echo "HYPERV_SHOULD_BE_PRESENT=true" >> $GITHUB_ENV
          echo "HYPERV_SHOULD_HAVE_STABLE_API=false" >> $GITHUB_ENV
          ls -al /dev/mshv
          whoami

      - name: Set up env vars for kvm-linux tests
        if: ${{ (matrix.hypervisor == 'kvm') && (runner.os == 'Linux') }}
        run: |
          sudo ls -al /dev/kvm
          sudo chgrp $(whoami) /dev/kvm
          sudo ls -al /dev/kvm
          echo "KVM_SHOULD_BE_PRESENT=true" >> $GITHUB_ENV

      ### Benchmarks ###

      # TODO: follow up with PR to download latest release benchmarks here to compare
      
      - name: Run Benchmarks
        run: |
          just bench-ci dev release

      # Upload new benchmark
      - uses: actions/upload-artifact@v3
        with: 
          name: benchmarks_${{runner.os}}_${{matrix.hypervisor}}
          path: ./target/criterion/
          if-no-files-found: error
