name: Benchmarks

on:
  workflow_call: # this is called from CreateRelease.yml
    secrets:
      ADO_CARGO_RO_PAT:
        required: true

jobs:
  build-host-library:
    uses: ./.github/workflows/dep_build_host_library.yml
    secrets: inherit
  build-guest-binaries:
    uses: ./.github/workflows/dep_build_guest_binaries.yml
    needs: [build-host-library]

  benchmark:
    needs: [build-guest-binaries]
    strategy:
      fail-fast: true
      matrix:
        build: [windows-2022-release, linux-kvm-release, linux-hyperv-release]
        include:
          - build: windows-2022-release
            os: [self-hosted, Windows, X64, "1ES.Pool=HL-Windows-2022"]
            hypervisor: none
          - build: linux-kvm-release
            os: [self-hosted, Linux, X64, "1ES.Pool=HL-Ubuntu-20.04-KVM"]
            hypervisor: kvm
          - build: linux-hyperv-release
            os: [self-hosted, Linux, X64, "1ES.Pool=HL-CBLMariner-mshv"]
            hypervisor: hyperv
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/hyperlight-workflows-setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT: ${{ secrets.ADO_CARGO_RO_PAT }}

      - name: Enable WHP on Windows
        if: ${{ (runner.os == 'Windows')}}
        run: Enable-WindowsOptionalFeature -Online -FeatureName HyperVisorPlatform
        shell: pwsh


      - name: Download Guest Binaries
        uses: actions/download-artifact@v3
        with:
          name: guest-binaries-release
          path: ./
      - name: Copy Guest Binaries
        run: |
          echo "Copying callbackguest binary for build config release"
          mkdir -p ./src/tests/Hyperlight.Tests/bin/release/net6.0/
          cp ./Guests/callbackguest/x64/release/callbackguest.exe ./src/tests/Hyperlight.Tests/bin/release/net6.0/callbackguest.exe
          mkdir -p ./src/tests/Guests/callbackguest/x64/release
          cp ./Guests/callbackguest/x64/release/callbackguest.exe ./src/tests/Guests/callbackguest/x64/release/callbackguest.exe
          echo "Copying simpleguest and dummyguest binaries for build config release"
          cp ./rust_guests/simpleguest/target/x86_64-pc-windows-msvc/release/simpleguest.exe ./src/tests/rust_guests/bin/release/simpleguest.exe
          cp ./rust_guests/dummyguest/target/x86_64-pc-windows-msvc/release/dummyguest.exe ./src/tests/rust_guests/bin/release/dummyguest.exe
      - name: Display Guest Binaries
        run: |
          echo "Displaying callbackguest binary in ./src/tests/Hyperlight.Tests/bin/release/net6.0"
          ls ./src/tests/Hyperlight.Tests/bin/release/net6.0/
          echo "Displaying simpleguest and dummyguest binaries in ./src/tests/rust_guests/bin/release/"
          ls ./src/tests/rust_guests/bin/release/
          
      - name: Set up env vars for hyperv-linux tests
        if: ${{ (matrix.hypervisor == 'hyperv') && (runner.os == 'Linux') }}
        run: |
          echo "HYPERV_SHOULD_BE_PRESENT=true" >> $GITHUB_ENV
          echo "HYPERV_SHOULD_HAVE_STABLE_API=false" >> $GITHUB_ENV
          ls -al /dev/mshv
          whoami

      - name: Set up env vars for kvm-linux tests
        if: ${{ (matrix.hypervisor == 'kvm') && (runner.os == 'Linux') }}
        run: |
          sudo ls -al /dev/kvm
          sudo chgrp $(whoami) /dev/kvm
          sudo ls -al /dev/kvm
          echo "KVM_SHOULD_BE_PRESENT=true" >> $GITHUB_ENV

      ### Benchmarks ###

      # Install GH cli
      - name: Install github-cli (Linux mariner)
        if: runner.os == 'Linux' && matrix.hypervisor == 'hyperv'
        run: sudo dnf install gh -y
      - name: Install github-cli (Linux ubuntu)
        if: runner.os == 'Linux' && matrix.hypervisor == 'kvm'
        run: sudo apt install gh -y

      - name: Fetch tags
        run: |
          git fetch --tags origin

      - name: Download benchmarks from most recent release
        run: |
          just bench-download ${{ runner.os }} ${{ matrix.hypervisor }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Benchmarks
        run: |
          just bench-ci dev release

      # Upload new benchmark
      - uses: actions/upload-artifact@v3
        with: 
          name: benchmarks_${{runner.os}}_${{matrix.hypervisor}}
          path: ./target/criterion/
          if-no-files-found: error
