# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build Host Library

# this is a workflow intended for use a dependency of other Hyperlight
# workflows. as such, it does not have any triggers other than "workflow_call"
#
# for more details on this trigger, see this link:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_call

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  #####
  # start build-host-library
  #####
  build-host-library:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        build: [ubuntu-20.04-debug, windows-2022-debug, ubuntu-20.04-release, windows-2022-release]
        include:
          - build: ubuntu-20.04-debug
            os: ubuntu-20.04
            config: debug
          - build: windows-2022-debug
            os: windows-2022
            config: debug
          - build: ubuntu-20.04-release
            os: ubuntu-20.04
            config: release
          - build: windows-2022-release
            os: windows-2022
            config: release
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Just
      uses: extractions/setup-just@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        just-version: '1.5.0' # optional semver specification, otherwise latest
    - name: Build hyperlight_host library
      working-directory: src/hyperlight_host
      run: just build ${{ matrix.config }}
      env:
        RUST_BACKTRACE: 1
    - name: upload hyperlight_host.h
      uses: actions/upload-artifact@v3
      with:
        name: hyperlight_host.h
        path: src/hyperlight_host/include/hyperlight_host.h
    - name: upload hyperlight_host.dll (Windows only)
      uses: actions/upload-artifact@v3
      if: runner.os == 'Windows'
      with:
        name: ${{ matrix.config }}_assets
        path: target/${{ matrix.config }}/hyperlight_host.dll
    - name: upload libhyperlight_host.so (Linux only)
      uses: actions/upload-artifact@v3
      if: runner.os == 'Linux'
      with:
        name: ${{ matrix.config }}_assets
        path: |
          target/${{ matrix.config }}/libhyperlight_host.so
          target/${{ matrix.config }}/libhyperlight_host.d
