# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish crates to intenral cargo registry

on:
  workflow_dispatch:

jobs:
  publish-hyperlight-packages:
    runs-on: ubuntu-latest
    if:  ${{ contains(github.ref, 'refs/heads/release/') }} 
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/hyperlight-workflows-setup
        env:
          PAT: ${{ secrets.ADO_CARGO_RW_PAT }}
      - name: set up cargo workspaces version
        run: |
          cargo install cargo-workspaces
          cargo install minver_rs
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.Name "${{ github.actor }}"
      - name: set crate versions
        run: |
          git fetch --tags
          version=$(MINVER_TAG_PREFIX=v minver)
          echo "version=$version"
          cargo ws version --force=hyperlight_* --no-git-tag --no-git-push --allow-branch=release/* --yes custom $version
      - name: Publish hyperlight-testing
        run: cargo publish --manifest-path ./src/hyperlight_testing/Cargo.toml --registry hyperlight_packages
      - name: Publish hyperlight-host 
        run: cargo publish --manifest-path ./src/hyperlight_host/Cargo.toml --registry hyperlight_packages
      - name: Publish hyperlight-capi
        # --no-verify is needed because the build.rs script generates ./include/hyperlight_capi.h 
        # and cargo does not want you to modify files outside of OUT_DIR
        run: cargo publish --manifest-path ./src/hyperlight_capi/Cargo.toml --registry hyperlight_packages --no-verify
      - name: Publish hyperlight-flatbuffers
        run: cargo +nightly publish --manifest-path ./src/hyperlight_flatbuffers/Cargo.toml --registry hyperlight_packages


