# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish crates to intenral cargo registry

on:
  workflow_dispatch:

jobs:
  publish-hyperlight_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.71.0
        with:
          components: clippy, rustfmt
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          just-version: '1.5.0' # optional semver specification, otherwise latest
      # We need to use the nightly rust tool change to enable registry-auth / to connec to ADO feeds.
      - name: rustup nightly
        run: rustup default nightly
      - name: Cargo login
        env:
          PAT: ${{ secrets.ADO_CARGO_RW_PAT}}
        run: just cargo-login-ci
      - name: Publish hyperlight-testing
        run: cargo publish --dry-run --manifest-path ./src/hyperlight_testing/Cargo.toml --registry hyperlight_packages

  publish-hyperlight_host:
    runs-on: ubuntu-latest
    needs:
      - publish-hyperlight_testing
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.71.0
        with:
          components: clippy, rustfmt
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          just-version: '1.5.0' # optional semver specification, otherwise latest
      # We need to use the nightly rust tool change to enable registry-auth / to connec to ADO feeds.
      - name: rustup nightly
        run: rustup default nightly
      - name: Cargo login
        env:
          PAT: ${{ secrets.ADO_CARGO_RW_PAT}}
        run: just cargo-login-ci
      - name: Publish hyperlight-host 
        # --no-verify is needed because the build.rs script generates ./include/hyperlight_host.h 
        # and cargo does not want you to omdify files outside of OUT_DIR
        run: cargo publish --dry-run --manifest-path ./src/hyperlight_host/Cargo.toml --registry hyperlight_packages --no-verify

  publish-hyperlight_capi:
    runs-on: ubuntu-latest
    needs:
      - publish-hyperlight_host
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.71.0
        with:
          components: clippy, rustfmt
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          just-version: '1.5.0' # optional semver specification, otherwise latest
      # We need to use the nightly rust tool change to enable registry-auth / to connec to ADO feeds.
      - name: rustup nightly
        run: rustup default nightly
      - name: Cargo login
        env:
          PAT: ${{ secrets.ADO_CARGO_RW_PAT}}
        run: just cargo-login-ci
      - name: Publish hyperlight-capi
        run: cargo publish --manifest-path ./src/hyperlight_capi/Cargo.toml --registry  --no-verify


