# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish crates to intenral cargo registry

on:
  workflow_dispatch:

jobs:
  publish-hyperlight-packages:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'refs/heads/release/') }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/hyperlight-workflows-setup
        env:
          PAT: ${{ secrets.ADO_CARGO_RW_PAT }}

      - name: Publish hyperlight-flatbuffers
        run: cargo publish --manifest-path ./src/hyperlight_flatbuffers/Cargo.toml --registry hyperlight_packages 

      - name: Publish hyperlight-guest
        run: cargo publish --manifest-path ./src/hyperlight_guest/Cargo.toml --registry hyperlight_packages 

      - name: Publish hyperlight-host
        run: cargo publish --manifest-path ./src/hyperlight_host/Cargo.toml --registry hyperlight_packages 

      # `--no-verify` is needed because the build.rs script generates ./include/hyperlight_capi.h
      # and cargo does not want you to modify files outside of OUT_DIR
      - name: Publish hyperlight-capi
        run: cargo publish --manifest-path ./src/hyperlight_capi/Cargo.toml --registry hyperlight_packages --no-verify 

      - name: Publish hyperlight-guestlib-c-includes
        run: cargo publish --manifest-path ./src/HyperlightGuest/Cargo.toml --registry hyperlight_packages 
