# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build hyperlight_capi

on:
  workflow_call:
    secrets:
      ADO_CARGO_RO_PAT:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  # this job has no dependencies
  build-hyperlight-capi:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        build:
          [
            ubuntu-20.04-debug,
            windows-2022-debug,
            ubuntu-20.04-release,
            windows-2022-release,
          ]
        include:
          - build: ubuntu-20.04-debug
            os: ubuntu-20.04
            config: debug
          - build: windows-2022-debug
            os: windows-2022
            config: debug
          - build: ubuntu-20.04-release
            os: ubuntu-20.04
            config: release
          - build: windows-2022-release
            os: windows-2022
            config: release

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/hyperlight-workflows-setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT: ${{ secrets.ADO_CARGO_RO_PAT }}

      - name: Build hyperlight_capi library
        run: |
          cd src/hyperlight_capi
          just build ${{ matrix.config }}
        env:
          RUST_BACKTRACE: 1

      - name: Upload hyperlight_capi.h
        uses: actions/upload-artifact@v3
        with:
          name: hyperlight_capi.h
          path: src/hyperlight_capi/include/hyperlight_capi.h

      - name: Upload hyperlight_capi.dll (Windows only)
        uses: actions/upload-artifact@v3
        if: runner.os == 'Windows'
        with:
          name: ${{ matrix.config }}_assets
          path: |
            target/${{ matrix.config }}/hyperlight_capi.dll
            target/${{ matrix.config }}/hyperlight_capi.pdb

      - name: Upload libhyperlight_capi.so (Linux only)
        uses: actions/upload-artifact@v3
        if: runner.os == 'Linux'
        with:
          name: ${{ matrix.config }}_assets
          path: |
            target/${{ matrix.config }}/libhyperlight_capi.so
            target/${{ matrix.config }}/libhyperlight_capi.d
