# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build Guest Binaries

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

env:
  CARGO_TERM_COLOR: always

permissions:
  id-token: write
  contents: read
  
jobs:
  # this job has no dependencies
  build-guest-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        build: [windows-2022-debug, windows-2022-release]
        include:
          - build: windows-2022-debug
            os: windows-2022
            config: debug
          - build: windows-2022-release
            os: windows-2022
            config: release

    steps:
      - uses: actions/checkout@v4

      - uses: deislabs/hyperlight-workflow-setup@v1.1.0
        with:
          rust-toolchain: "1.74.0"
          azure-client-id: ${{ secrets.ADO_HYPERLIGHT_CARGO_RO_AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and move Rust guests
        run: just build-and-move-rust-guests

      - name: Upload Binary Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: guest-binaries-${{ matrix.config }}
          path: |
            src\tests\rust_guests\bin\${{ matrix.config }}\callbackguest.exe
            src\tests\rust_guests\bin\${{ matrix.config }}\dummyguest.exe
            src\tests\rust_guests\bin\${{ matrix.config }}\simpleguest.exe
          if-no-files-found: error
