name: Fuzzing Workflow

on:
  schedule:
    - cron: '0 0 * * 0' # Runs at 00:00 every Sunday
  workflow_dispatch: # Allow manual triggering

jobs:
  fuzzing:
    uses: ./.github/workflows/dep_fuzzing.yml
    with:
      max_total_time: 86400 # 24 hours in seconds
    secrets: inherit