name: Fuzzing Workflow

on:
  schedule:
    - cron: '0 0 * * 0' # Runs at 00:00 every Sunday
  workflow_dispatch: # Allow manual triggering

jobs:
  build-guest-binaries:
    uses: ./.github/workflows/dep_build_guest_binaries.yml
    
  fuzzing:
    needs: [build-guest-binaries]
    uses: ./.github/workflows/dep_fuzzing.yml
    with:
      max_total_time: 18000 # 5 hours in seconds
    secrets: inherit