# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build Hyperlight development image - Ubuntu w/ KVM

on:
  pull_request:
    branches: [ dev ]
    paths:
      - '.github/workflows/ImageBuilder_Ubuntu_kvm.yml'
      - 'dev/packer/**'
  schedule:
    - cron: '0 1 * * 0' # Runs at 01:00 UTC every Sunday
  workflow_dispatch:
    inputs:
      machine_size:
        description: 'Build machine size'
        required: true
        default: 'Standard_D4as_v5'
      location:
        description: 'Location to build and store the image'
        required: true
        default: 'westus3'

# This job will build and publish a Hyperlight development image to a Shared Image Gallery.
# Packer is configured to use Azure CLI authentication using ODIC credentials.

permissions:
  id-token: write
  contents: read

env:
  PRODUCT_VERSION: "latest"

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZ_IMAGE_BUILDER_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_IMAGE_BUILDER_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_IMAGE_BUILDER_SUB_ID }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@v3.1.0
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run `packer init`
        id: init
        run: "packer init ./dev/packer/ubuntu-kvm.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./dev/packer/ubuntu-kvm.pkr.hcl"

      - name: Run `packer build` (ci)
        if: ${{ github.event_name == 'pull_request' }}
        id: build-ci
        # force here is used to overwrite the managed image that gets created in the build process
        run: "packer build -force -color=false ./dev/packer/ubuntu-kvm.pkr.hcl"

      - name: Run `packer build`
        if: ${{ github.event_name != 'pull_request' }}
        id: build
        # force here is used to overwrite the managed image that gets created in the build process
        run: "packer build -var 'vm_size=${{ github.event.inputs.machine_size || 'Standard_D4as_v5' }}' -var 'location=${{ github.event.inputs.location || 'westus3' }}' -var 'image_name=ubuntu-kvm-dev' -force -color=false ./dev/packer/ubuntu-kvm.pkr.hcl"
