# TODO: When Github Actions allows Reusable Workflows with strategies then move build test to a reuasble workflow.
# https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations

name: Push to main

on:
  push:
    branches: [ main ]
  
jobs:
  publish:
    runs-on: windows-latest
    env:
      PLATFORM: x64
      CONFIG: debug
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore
      run: dotnet restore
      shell: pwsh
    - name: Set MINVERBUILDMETADATA
      run:  echo "MINVERBUILDMETADATA=$(git rev-parse --short ${{ github.sha }})" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    # Need to build the native guest projects first to make sure the solution build succeeds, this can be done by placing dependencies in the test project but doing this causes dotnet test to fail.
    - name: Build Native Guests
      run: msbuild hyperlight.sln /p:Configuration=$env:CONFIG /p:Platform=$env:PLATFORM /t:Test\Guests\callbackguest /t:Test\Guests\simpleguest -m:2
      shell: pwsh
    - name: Build Solution
      run: msbuild hyperlight.sln /p:Configuration=$env:CONFIG /p:Platform=$env:PLATFORM /p:ContinuousIntegrationBuild=true
      shell: pwsh
    - name: Test
      shell: pwsh
      run: dotnet test -c $env:CONFIG
      working-directory: src/tests/Hyperlight.Tests
    - name: Package templates
      run: dotnet pack -c $env:CONFIG --include-symbols -p:RepositoryUrl=https://github.com/${{ github.repository }}.git 
      working-directory: src/Hyperlight
      shell: pwsh
    - name: Publish Github Packages
      run: |
           for nupkg in $(find . -name *.nupkg)
           do
            echo Pushing $nupkg
            dotnet nuget push $nupkg --api-key ${{ secrets.GHPACKAGES_PAT }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
           done
      shell: bash
      working-directory: src/Hyperlight