name: Rust Tests and Lints

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        build: [ubuntu-20.04-debug, windows-2022-debug, linux-kvm-debug, linux-hyperv-debug, ubuntu-20.04-release, windows-2022-release, linux-kvm-release, linux-hyperv-release]
        include:
          - build: ubuntu-20.04-debug
            os: ubuntu-20.04
            hypervisor: none
            config: debug
          - build: windows-2022-debug
            os: windows-2022
            hypervisor: none
            config: debug
          - build: linux-kvm-debug
            os: [self-hosted, Linux, X64, kvm2]
            hypervisor: kvm
            config: debug
          - build: linux-hyperv-debug
            os: [self-hosted, Linux, X64, hyperv-nov82022]
            hypervisor: hyperv
            config: debug
          - build: ubuntu-20.04-release
            os: ubuntu-20.04
            hypervisor: none
            config: release
          - build: windows-2022-release
            os: windows-2022
            hypervisor: none
            config: release
          - build: linux-kvm-release
            os: [self-hosted, Linux, X64, kvm2]
            hypervisor: kvm
            config: release
          - build: linux-hyperv-release
            os: [self-hosted, Linux, X64, hyperv-nov82022]
            hypervisor: hyperv
            config: release
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.64.0
          override: true
          default: true
          profile: default
      - uses: Swatinem/rust-cache@v2
      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Install Just
        uses: extractions/setup-just@v1
        with:
          just-version: '1.5.0' # optional semver specification, otherwise latest
      - name: Build
        working-directory: src/hyperlight_host
        run:  just build ${{ matrix.config }}
      - name: Set up env vars for hyperv-linux tests
        if: ${{ (matrix.hypervisor == 'hyperv') && (runner.os == 'Linux') }}
        run: |
          echo "HYPERV_SHOULD_BE_PRESENT=true" >> $GITHUB_ENV
          echo "SHOULD_HAVE_STABLE_API=false" >> $GITHUB_ENV
      - name: Set up env vars for kvm-linux tests
        if: ${{ (matrix.hypervisor == 'kvm') && (runner.os == 'Linux') }}
        run: |
          echo "KVM_SHOULD_BE_PRESENT=true" >> $GITHUB_ENV
      - name: Run Rust tests
        working-directory: src/hyperlight_host
        run: just build-test-rust ${{ matrix.config }}
      - name: Set up munit
        working-directory: src/hyperlight_host/tests_capi
        run: |
          git submodule init
          git submodule update
      - name: Run C Tests 
        working-directory: src/hyperlight_host
        run: |
          echo "testdata:"
          ls testdata
          just run-tests-capi  ${{ matrix.config }}
      # Script to install Valgrind does not work on Mariner or on the kvm 
      # runner. Valgrind has been installed manually on the runners.
      - name: Install Valgrind (Linux only - not hyperv)
        if: ${{ (matrix.hypervisor != 'hyperv') && (matrix.hypervisor != 'kvm') && (runner.os == 'Linux') }}
        run: ./install_valgrind.sh
        working-directory: ./scripts
      - name: Valgrind C tests (Linux only)
        working-directory: src/hyperlight_host
        if: runner.os == 'Linux'
        run: just valgrind-tests-capi  ${{ matrix.config }}
