# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: hyperlight-project-board-sync

on:
  schedule:
    - cron: "0 14 * * *" # Every day at 14:00 UTC / 6:00 PST
  workflow_dispatch:

jobs:
  build:
    name: hyperlight-project-board-sync
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: sync Hyperlight project - deislabs org
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_PROJECTS_PAT }}
        run: |
          ./dev/sync-project-board.sh