# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Validate Pull Request

on:
  pull_request:
    branches: [main, dev, "release/**"]
  merge_group:

permissions:
  id-token: write
  contents: read

jobs:

  rust:
    uses: ./.github/workflows/dep_rust.yml
    secrets: inherit
  fuzzing:
    uses: ./.github/workflows/dep_fuzzing.yml
    with:
      max_total_time: 300 # 5 minutes in seconds
    secrets: inherit

  #####
  # start build-on-windows
  #####
  build-on-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        build: [windows-debug, windows-release]
        include:
          - build: windows-debug
            os: [self-hosted, Windows, X64, "1ES.Pool=HL-win-2022-amd"]
            config: debug
            platform: x64
          - build: windows-release
            os: [self-hosted, Windows, X64, "1ES.Pool=HL-win-2022-amd"]
            config: release
            platform: x64
    env:
      DOTNET_INSTALL_DIR: "./.dotnet"
      RUST_BACKTRACE: FULL

    steps:
      - uses: actions/checkout@v4

      - name: Get system info
        run: |
          echo "cmd /ver"
          cmd /ver
          echo "systeminfo"
          systeminfo

      # Run this so we can use just targets in this workflow
      - uses: deislabs/hyperlight-workflow-setup@v1.3.0
        with:
          rust-toolchain: "1.78.0"
          azure-client-id: ${{ secrets.ADO_HYPERLIGHT_CARGO_RO_AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # This is a workaround for the issue described at https://github.com/dotnet/sourcelink/issues/675 ,
      # it supresses the warning about the sourcelink package not being found.
      - name: Remove Submodule
        run: git rm munit
        shell: pwsh
        working-directory: src/hyperlight_capi/tests_capi

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 6.0.x

      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Restore
        run: dotnet restore
        shell: pwsh

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build hyperlight_capi.dll
        run: |
          cd src/hyperlight_capi
          just build ${{ matrix.config }}

      - name: Fetch printf
        working-directory: src/HyperlightGuest/third_party/printf
        run: git submodule update --init
      - name: Set up WHP_SHOULD_BE_PRESENT Env Var
        run: |
          echo "WHP_SHOULD_BE_PRESENT=true" >> $GITHUB_ENV

      - name: Build and Move Guest Binaries
        run: |
          just build-rust-guests ${{ matrix.config }}
          just move-rust-guests ${{ matrix.config }}

      - name: Build C Guest Binaries
        run: |
          just build-c-guests ${{ matrix.config }}

      - name: Build Solution
        run: msbuild -m hyperlight.sln /p:Configuration=${{ matrix.config }} /p:Platform=${{ matrix.platform }} /p:ContinuousIntegrationBuild=true
        shell: pwsh

      - name: Test dotnet with rust guests
        shell: pwsh
        run: dotnet test -c ${{ matrix.config }} --logger "trx;verbosity=detailed;LogFilePrefix=win-${{ matrix.config }}" --blame
        working-directory: src/tests/Hyperlight.Tests

      - name: Build Example
        shell: pwsh
        run: dotnet build -c ${{ matrix.config }}
        working-directory: src/examples/NativeHost

      - name: Run Example with rust guests
        shell: pwsh
        run: dotnet run -c ${{ matrix.config }} -- -nowait
        working-directory: src/examples/NativeHost

      - name: Test dotnet with c guests
        shell: pwsh
        run: |
          just test-dotnet-c-guests ${{ matrix.config }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.config }}
          path: src\tests\Hyperlight.Tests\TestResults\*.trx

  #####
  # end build-on-windows
  #####

  #####
  # start build-on-linux
  #####
  build-on-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        build:
          [
            linux-kvm-debug,
            linux-kvm-release,
            linux-hyperv-debug,
            linux-hyperv-release,
          ]
        include:
          - build: linux-kvm-debug
            os: [self-hosted, Linux, X64, "1ES.Pool=HL-Ubuntu-20.04-KVM"]
            config: debug
            platform: x64
            hypervisor: kvm
          - build: linux-kvm-release
            os: [self-hosted, Linux, X64, "1ES.Pool=HL-Ubuntu-20.04-KVM"]
            config: release
            platform: x64
            hypervisor: kvm
          - build: linux-hyperv-debug
            os: [self-hosted, Linux, X64, "1ES.Pool=HL-mshv-dev"]
            config: debug
            platform: x64
            hypervisor: hyperv
          - build: linux-hyperv-release
            os: [self-hosted, Linux, X64, "1ES.Pool=HL-mshv-dev"]
            config: release
            platform: x64
            hypervisor: hyperv
    env:
      RUST_BACKTRACE: FULL

    steps:
      - uses: actions/checkout@v4
      # This is a workaround for the issue described at https://github.com/dotnet/sourcelink/issues/675 ,
      # it supresses the warning about the sourcelink package not being found.
      - name: Remove Submodule
        run: git rm munit
        shell: bash
        working-directory: src/hyperlight_capi/tests_capi

      - name: uname (linux)
        run: |
          echo "uname -a"
          uname -a
          echo "cat /etc/os-release"
          cat /etc/os-release

      - uses: deislabs/hyperlight-workflow-setup@v1.3.0
        with:
          rust-toolchain: "1.78.0"
          azure-client-id: ${{ secrets.ADO_HYPERLIGHT_CARGO_RO_AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup dotnet (not on hyperv)
        if: ${{ (matrix.hypervisor != 'hyperv') }}
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 6.0.x

      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Build and Move Guest Binaries
        run: |
          just build-rust-guests ${{ matrix.config }}
          just move-rust-guests ${{ matrix.config }}

      - name: Build hyperlight_capi.so
        run: |
          cd src/hyperlight_capi
          just build ${{ matrix.config }}

      - name: Restore
        run: dotnet restore
        shell: bash

      - name: Build Hyperlight
        shell: bash
        run: dotnet build -c ${{ matrix.config }}
        working-directory: src/Hyperlight

        # Only clean the example if we're on a self-hosted
        # runner. GitHub hosted runners are automatically
        # cleaned.
      - name: Clean example
        shell: bash
        run: dotnet clean -c ${{ matrix.config }}
        working-directory: src/examples/NativeHost
        if: ${{ matrix.os }} == 'self-hosted'

      - name: Build C Guest Binaries
        run: |
          just build-c-guests ${{ matrix.config }}

      - name: Run Example
        shell: bash
        run: dotnet run -c ${{ matrix.config }} -- -nowait
        working-directory: src/examples/NativeHost

      - name: Test
        shell: bash
        run: dotnet test -c ${{ matrix.config }} --logger "trx;verbosity=detailed;LogFilePrefix=linux-${{ matrix.config }}-${{ matrix.hypervisor }}" --blame
        working-directory: src/tests/Hyperlight.Tests

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.config }}-${{ matrix.hypervisor }}
          path: src/tests/Hyperlight.Tests/TestResults/*.trx
  #####
  # end build-on-linux
  #####