# TODO: When Github Actions allows Reusable Workflows with strategies then move build test to a reuasble workflow.
# https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations

name: Validate Pull Request

on:
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        build: [ windows-debug ]
        include:
          - build: windows-debug
            os: windows-latest
            config: debug
            platform: x64
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore
      run: dotnet restore
      shell: pwsh
    - name: Set MINVERBUILDMETADATA
      run:  echo "MINVERBUILDMETADATA=$(git rev-parse --short ${{ github.sha }})" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    # Need to build the native guest projects first to make sure the solution build succeeds, this can be done by placing dependencies in the test project but doing this causes dotnet test to fail.
    - name: Build Native Guests
      run: msbuild hyperlight.sln /p:Configuration=${{ matrix.config }} /p:Platform=${{ matrix.platform }} /t:Test\Guests\callbackguest /t:Test\Guests\simpleguest -m:2
      shell: pwsh
    - name: Build Solution
      run: msbuild hyperlight.sln /p:Configuration=${{ matrix.config }} /p:Platform=${{ matrix.platform }} /p:ContinuousIntegrationBuild=true
      shell: pwsh
    - name: Test
      shell: pwsh
      run: dotnet test -c ${{ matrix.config }}
      working-directory: src/tests/Hyperlight.Tests